version: 2.1

orbs:
  cypress: cypress-io/cypress@3
executors:
  default:
    docker:
      - image: cimg/node:20.10.0-browsers
    parameters:
      node-version:
        default: 20.10.0
        type: string
workflows:
  test:
    jobs:
      - cypress/run:
          package-manager: "yarn"
          start-command: "yarn ci:run"
