version: 2.1

orbs:
  cypress: cypress-io/cypress@3

jobs:
  build:
    docker:
      - image: cimg/node:20.10.0-browsers

    steps:
      - checkout
      - run:
          name: Install Yarn
          command: npm install -g yarn
      - run:
          name: Yarn Install
          command: yarn install

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - cypress/run:
          requires:
            - build # build 작업이 먼저 실행된 후 cypress/run 실행
          package-manager: yarn
          start-command: yarn start
