version: 2.1

orbs:
  cypress: cypress-io/cypress@3

jobs:
  build:
    docker:
      - image: cimg/node:20.10.0-browsers # Node.js 버전 20 사용
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: nvm install 20.10.0
      - run:
          name: Use Node.js
          command: nvm use 20.10.0
      - run:
          name: Install Yarn
          command: npm install --force -g yarn
      - run:
          name: Yarn Install
          command: yarn install --frozen-lockfile

workflows:
  build_and_test:
    jobs:
      - build
      - cypress/run:
          requires:
            - build
          package-manager: yarn
          start-command: yarn start
