version: 2.1

orbs:
  cypress: cypress-io/cypress@3

jobs:
  build:
    docker:
      - image: cimg/node:20.10.0-browsers # Node.js 버전 20 사용
    steps:
      - checkout
      - run:
          name: Confirm Node.js version
          command: node -v
      - run:
          name: Install Yarn
          command: npm install --force -g yarn
      - run:
          name: Yarn Install
          command: yarn --frozen-lockfile
      - run:
          name: Cypress Headless Tests
          command: yarn cy:run

workflows:
  build_and_test:
    jobs:
      - build
