import Footer from "@/components/footer/Footer";
import NavBar from "@/components/header/NavBar";
import SWRConfigContext from "@/context/SWRConfigContext";
import { NextUIProvider } from "@nextui-org/system";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pocket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SWRConfigContext>
          <NextUIProvider>
            <NavBar />
            {children}
            <Footer />
          </NextUIProvider>
        </SWRConfigContext>
      </body>
    </html>
  );
}
